# Generated by Django 2.0.5 on 2018-05-02 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('foto', models.ImageField(upload_to='fotos_articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=16)),
                ('puerto', models.IntegerField()),
                ('motor', models.CharField(choices=[('', (('postgres', 'Postgres'),)), ('', (('oracle', 'Oracle'),)), ('', (('mysql', 'Mysql'),))], max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(blank=True, max_length=50)),
                ('bd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=100)),
                ('extension', models.CharField(blank=True, max_length=50)),
                ('linea_directa', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('latitud', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('', (('administrativo', 'Administrativo'),)), ('', (('docente', 'Docente'),)), ('', (('estudiante', 'Estudiante'),)), ('', (('docente, estudiante', 'Docente, Estudiante'),)), ('', (('administrativo, docente', 'Administrativo, Docente'),)), ('', (('administrativo, docente, estudiante', 'Administrativo, Docente, Estudiante'),)), ('', (('publico', 'Público'),))], max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('sql', models.TextField(max_length=500)),
                ('descripcion', models.TextField(max_length=300)),
                ('conexion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapp.Conexion')),
            ],
        ),
    ]
