# Generated by Django 2.0.5 on 2018-05-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_parametrizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='foto',
            field=models.ImageField(upload_to='fotos_articulo/'),
        ),
    ]
