# Generated by Django 2.0.5 on 2018-05-19 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20180518_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='conexion',
            old_name='ip',
            new_name='ip_servidor',
        ),
        migrations.RemoveField(
            model_name='conexion',
            name='bd',
        ),
        migrations.AddField(
            model_name='base_datos',
            name='conexion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapp.Conexion'),
        ),
    ]
