# Generated by Django 2.0.5 on 2018-05-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20180518_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_datos',
            name='conexion',
        ),
        migrations.AddField(
            model_name='conexion',
            name='nombre_bd',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Base_datos',
        ),
    ]
