# Generated by Django 2.0.5 on 2018-05-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_auto_20180519_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conexion',
            name='nombre_bd',
            field=models.CharField(max_length=50),
        ),
    ]
