# Generated by Django 2.0.6 on 2018-07-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_auto_20180519_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrizacion',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='fotos_param'),
        ),
    ]
