# Generated by Django 2.0.6 on 2018-07-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_remove_parametrizacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrizacion',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='fotos_param'),
        ),
    ]
