# Generated by Django 2.0.6 on 2018-07-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_parametrizacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrizacion',
            name='imagen',
            field=models.ImageField(upload_to='fotos_param'),
        ),
    ]
